### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by fessoga5** [Romastyi/VLC-VK-Music#1]
Hello! Don't work in win7 64 with vlc (64x) 2.1.5.

qt4 debug: activating or triggering extension 'VK Music'
lua debug: Activating extension 'VK Music'
lua warning: Error loading script C:\Program Files\VideoLAN\VLC\lua\extensions\vkmusic.lua: ...rogram Files\VideoLAN\VLC\lua\extensions\vkmusic.lua:17: module 'common' not found: no field package.preload['common'] no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.luac' no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.lua' no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.vle' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.luac' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.lua' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.vle' no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.luac' no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.lua' no file 'C:\Program Files\VideoLAN\VLC\lua\modules\common.vle' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.luac' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.lua' no file 'C:\Program Files\VideoLAN\VLC\lua\extensions\modules\common.vle' no file '.\common.lua' no file '!\lua\common.lua' no file '!\lua\common\init.lua' no file '!\common.lua' no file '!\common\init.lua' no file '.\common.dll' no file '!\common.dll' no file '!\loadall.dll'
lua error: Could not activate extension!
lua debug: Deactivating 'VK Music'
lua debug: Extension thread end: 'VK Music'

**Comment by Romastyi** [comment]
Hi! Thanks for the report.

To resolve your problem just copy file common.luac from %ProgramFiles%\VideoLAN\VLC\lua\intf\modules to %ProgramFiles%\VideoLAN\VLC\lua\modules and restart VLC player.

P.S.: With VLC 2.1.5 64bit version I've found some problems with HTTPS certificate (error: TLS certificate could not be verified) and could not find quick solution. But with 32bit version (VLC 2.1.5) this problem was not detected.

**Comment by fessoga5** [comment]
Thanks! It's work!

**Comment by kapkan** [comment]
Tnx Romastyi!
For OSX users: 
cp /Applications/VLC.app/Contents/MacOS/share/lua/intf/modules/common.luac /Applications/VLC.app/Contents/MacOS/share/lua/modules/
